[package]
name = "authentication"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-session = { version = "0.10.0", features = ["redis-session"] }
actix-web = "4.9.0"
argon2 = "0.5.3"
oauth2 = "4.4.2"
