services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
  authentication:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/usr/app:z

volumes:
  pgdata:
