services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"
  authentication-backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/app:z
  authentication-frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    restart: always
    extra_hosts:
      host.docker.internal: host-gateway
    ports:
      - "5173:5173"
    depends_on:
      - db
      - redis
      - authentication-backend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app:z

volumes:
  pgdata:
